### ISSUE TITLE
Failed training brain_extraction.py due to CUDA issues

### ISSUE THREAD

**Issue by hvgazula** [neuronets/nobrainer-book#11]
Running [this](https://github.com/neuronets/nobrainer-book/blob/master/docs/nobrainer-guides/scripts/03-train_brain_extraction.py) script fails with the following error on openmind A100 GPU.

`

> tensorflow.python.framework.errors_impl.InternalError: cudaGetDevice() failed. Status: CUDA driver version is insufficient for CUDA runtime version

`

Related to https://github.com/neuronets/nobrainer/issues/272

What did I try?
```
1. conda create -n no-brainer python=3.10 pip
2. pip install no-brainer
3. module load openmind8/cuda/12.1 && module load openmind8/cudnn/8.8.1-cuda12
4. conda activate nobrainer
5. python

>>> import tensorflow as tf
>>> tf.__version__
'2.15.0'
>>> tf.config.list_physical_devices('GPU')
[PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

--------------------------------------------------- /cm/shared/modulefiles ----------------------------------------------------
openmind8/cuda/11.7  openmind8/cudnn/8.7.0-cuda11  openmind8/cudnn/8.9.7-cuda11  
openmind8/cuda/12.1  openmind8/cudnn/8.8.1-cuda12  

```
https://www.tensorflow.org/install/source#gpu

<img width="702" alt="image" src="https://github.com/neuronets/nobrainer-book/assets/9400767/2afc2483-d878-48a3-8ca2-5df9ca46dd76">

**Comment by satra** [comment]
@hvgazula - this is an openmind issue rather than a nobrainer notebook issue. the openmind wiki has faq's on how to set up your conda/mamba environment for this with specific versions.
